# Preparation
library(gdata)
library(plyr)
library(dplyr)
library(data.table)
setwd("./git/fhhgb_ws19/ASC/r/project/")
source = data.table(read.xls("./deposit.xlsx"))
head(source)

unique(source$job)
unique(source$marital)
unique(source$housing)
unique(source$loan)
unique(source$contact)
unique(source$month)
unique(source$day_of_week)
unique(source$campaign)
unique(source$pdays)
unique(source$previous)
unique(source$poutcome)
unique(source$emp.var.rate)
unique(source$cons.price.idx)
unique(source$cons.conf.idx)
unique(source$euribor3m)
unique(source$nr.employed)
unique(source$y)
