version: "3"

services:
  redis:
    ports:
      - "6379:6379"
    container_name: "Redis"
    image: "redis:latest"
    command: redis-server --appendonly yes
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
