---
title: "gl05_3_hoermann"
author: "Paul Hörmann"
date: "11/30/2019"
output: pdf_document
---

# Aufgabe 3: Datensatz "Marketing"
```{r echo=F}
library(data.table)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
```
```{r}
dmarketing = data.table(read.csv("./Marketing.csv", sep = ";"))
head(dmarketing)
```

## a
```{r}
dmarketingEncoded <- mutate(dmarketing,
  Size = ifelse(MarketSize > 500, "Supermarkt",
                ifelse(MarketSize <= 301, "Geschaeft", "Markt")))
head(dmarketingEncoded)
```
```{r}
dSize = dmarketingEncoded %>% group_by(Size) %>% summarize(
  nr = length(LocationID)
)
dSize
```
```{r}
dmarketingEncoded %>% group_by(Promotion) %>% summarize(
  nr = length(LocationID)
)
```

## b
```{r}
ggplot(dmarketingEncoded, aes(x=Size, fill=Size)) + geom_histogram(position = "dodge",stat = "count")
```
```{r}
ggplot(dmarketingEncoded, aes(x=Promotion), fill=Psdfromotion) + geom_histogram(position = "dodge",stat = "count")
```

## c
```{r}
dmarketingByLoc = data.table(dmarketingEncoded %>% group_by(LocationID))

calculateSales = function (data, wstart, wend) {
  currentCompany = 0
  dLength = length(data$LocationID)
  data[, Diff := 0]
  index = 4 * currentCompany + 1
  while (index < dLength) {
    index = currentCompany * 4 + 1
    for (week in wstart:wend) {
      index = index + 1
      data[index]$Diff = data[index,]$Sales - data[index - 1,]$Sales
    }
    currentCompany = currentCompany + 1
  }
  data
}
dmarketingDiff = calculateSales(dmarketingByLoc, 2, 4)
```

Mittelwert Verkäufe erste Woche
```{r}
msw1 = colMeans(dmarketingByLoc %>% filter(Week == 1) %>% select(Sales))
msw1
```

Mittelwert +- SD
```{r}
sdsw1 = dmarketingByLoc %>% filter(Week == 1) %>% summarize(SD = sd(Sales))

paste(c(round(msw1), " +- ", round(sdsw1)), collapse = '')
```

Mittelwert & SD am Ende der Studie
```{r}
msw4 = colMeans(dmarketingByLoc %>% filter(Week == 4) %>% select(Sales))
sdsw4 = dmarketingByLoc %>% filter(Week == 4) %>% summarize(SD = sd(Sales))

paste(c(round(msw4), " +- ", round(sdsw4)), collapse = '')
```

Median, IQR & Spannweite zum Beginn der Studie
```{r}
statw1 = dmarketingByLoc %>% filter(Week == 1) %>% summarize(Median = median(Sales), IQR = IQR(Sales), range = paste(range(Sales), collapse = ' - '))
statw1
```

MW aller numerischen Werte
```{r}
mwnum = colMeans(dmarketingByLoc %>% select_if(is.numeric))
mwnum
```

MW Verkäufe gruppiert nach Geschäftsgröße
```{r}
statgsize = dmarketingByLoc %>% group_by(Size) %>% summarize(Mean = mean(Sales))
statgsize
```

## e
```{r}

```

## d
```{r}

```
